stages:
  - install
  - lint
  - test
  - deploy

cache:
  paths:
    - webapp/node_modules/

install_dependencies:
  stage: install
  image: node:20
  script:
    - cd webapp
    - npm ci
  only:
    - main
    - develop

run_lint:
  stage: lint
  image: node:20
  script:
    - cd webapp
    - npm run lint
  only:
    - main
    - develop

run_tests:
  stage: test
  image: node:20
  script:
    - cd webapp
    - npm test
  only:
    - main
    - develop

pages:
  stage: deploy
  image: node:20
  script:
    - cd webapp
    - npm run build
    - mkdir -p public
    - cp -r * public/
  artifacts:
    paths:
      - public
  only:
    - main